package.json, schema/debugger.json, src/debugger.ts, src/index.ts, src/sidebar.ts, src/tokens.ts, style/index.css, yarn.lock
* The `IDebugger` interface returned by the visual debugger `JupyterFrontEndPlugin` is a pool  (`IObjectPool<IDebugger.ISession>`) of debugger sessions.
* A debugger session `IDebugger.ISession` is composed of:
* `client: IClientSession`: the API client session to connect to a debugger
* `editors: CodeEditor.IEditor[]`: the code editors in a debugger session.
=> Visual debugger scaffolding.

.prettierrc, package.json
Add prettier git commit hook to automatically format code on `git commit`.
=> Add prettier git commit hook

package.json, tests/babel.config.js, tests/jest.config.js, tests/run-test.py, tests/src/debugger.spec.ts, tests/tsconfig.json, tsconfig.json
Add initial scaffolding for tests.
```bash
jlpm
jlpm run test
```
=> Add scaffolding for tests

src/index.ts, src/sidebar.ts, src/tokens.ts
=> Export IDebuggerSidebar plugin token.

src/handlers/cell.ts, src/index.ts, src/session.ts
=> Connect to debbuger 

package.json, src/breakpoints/index.ts, src/handlers/cell.ts, src/variables/body/search.tsx
Fix a few linting errors.
We should add a step in the test pipeline that does this check or a commit hook like prettier.
=> Fix linting

src/index.ts, src/tokens.ts
Fixing left over linting errors (with `jlpm run tslint`).
=> Fix linting errors

src/index.ts, src/session.ts
=> enable and disable commands based on replies

.prettierignore
To ignore some folders when formatting code automatically.
=> Add .prettierignore file

tests/src/session.spec.ts
Add a test for the `debugInfo` request added in #75.
=> Add test for debugInfo request

src/debugger.ts, src/index.ts, src/service.ts, src/tokens.ts
=> Continue, Next and StepIn commands

src/breakpoints/body.tsx, src/breakpoints/index.ts, src/debugger.ts, src/handlers/cell.ts, src/handlers/notebook.ts, src/index.ts, src/service.ts, src/tokens.ts
=> Set breakpoints via the service

src/index.ts, src/service.ts, src/tokens.ts
=> Add stepOut to the service and the command palette

src/index.ts, src/service.ts, src/session.ts, src/tokens.ts
This also includes a first pass on `IDebugger`, `IDebugger.ISession`, `DebugService` and `DebugSession` according to #139
=> Restore debugger state

azure-pipelines.yml, binder/environment.yml, package.json, src/breakpoints/body.tsx, src/breakpoints/index.ts, src/debugger.ts, src/handlers/cell.ts, src/service.ts, src/tokens.ts, tests/src/session.spec.ts
This PR breaks two features that need further refactoring to be restored:
- breakpoints activation from the breakpoint panel
- ~~restart does not send the breakpoints back to the kernel~~
EDIT: last feature has been restored.
=> The model now keeps all the breakpoints of a notebook

azure-pipelines.yml, binder/environment.yml, src/service.ts, src/tokens.ts, tests/src/session.spec.ts
=> Upgraded to xeus-python 0.6.6

.gitignore, src/debugger.ts, src/index.ts, src/service.ts, src/tokens.ts
=> Restores the stopped threads after a restoreState request

src/breakpoints/body.tsx, src/breakpoints/index.ts, style/breakpoints.css
resolved #213 
Backend, for now, don't support deactivate breakpoints. We just remove (commended) input checkbox and remove toolbar from breakpoints panel 'deactive all breakpoints'.
=> Remove deactivate breakpoint

src/index.ts
=> no throws error after close debugger

src/service.ts, src/tokens.ts, tests/src/service.spec.ts
=> IDebugger is not an IDisposable anymore

src/callstack/body.tsx, src/callstack/index.ts, src/handlers/tracker.ts, src/index.ts, src/sources/index.ts
Fixes #246.
Builds on top of #242 (to be rebased).
=> Open the source of a breakpoint on click

style/sidebar.css
=> Add drop shadows to headers

src/service.ts
A quick pass on `service.ts` to:
=> Update service.ts to keep a consistent style

src/service.ts, src/tokens.ts, tests/src/service.spec.ts
=> Make service.isStarted a getter

src/sources/index.ts
Part of #139. 
Format sources/index.ts according to the code style.
=> Format sources/index.ts according to the code style

src/index.ts
=> Remove close command

src/index.ts
=> Remove create command 

src/index.ts, src/service.ts
Fixes #277.
To try it out:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jtpio/debugger/kernel-changed?urlpath=/lab/tree/examples/index.ipynb)
=> Handle kernel changes

src/handlers/console.ts, src/handlers/editor.ts, src/handlers/file.ts, src/handlers/notebook.ts, src/handlers/tracker.ts
Part of #139.
Similar to previous PRs, this one is about formatting the handlers so the style stays consistent.
=> Format the handlers according to the code style

src/index.ts, src/session.ts
=> Handle kernel restarts

src/handlers/notebook.ts
=> Handle cell undos

src/index.ts
=> Check for widget focus when toggling debugging

src/breakpoints/body.tsx, style/breakpoints.css
=> Set truncate breakpoints paths at the beginning

src/index.ts
=> Set ILabShell with optional dependency

src/breakpoints/body.tsx, src/debugger.ts, src/header.ts, src/session.ts, src/tokens.ts, style/breakpoints.css, style/index.css, style/sidebar.css
=> Create header for sidebar debugger

src/handler.ts
=> Fix docstrings for the debugger handler

src/handler.ts
Fixes #322.
Follow-up on #337. 
This should improve the kernel restart logic:
=> Improve kernel restart handling

src/sources/header.tsx, style/sources.css
resolve #267 Clicking on the path should open the source
=> Make Clickable path for open the source

src/handlers/editor.ts
=> Fix, adding breakpoints after change path

package.json
=> v0.2.0-beta.1

README.md, azure-pipelines.yml, binder/environment.yml
cf. https://github.com/jupyterlab/debugger/issues/384
=> Wrap constraint arguments in `conda` command in quotation marks.

src/handler.ts, src/index.ts, src/service.ts, src/session.ts
=> Toggle life bug

src/variables/table.tsx, src/variables/tree.tsx, style/variables.css
Replaces #396. 
- Filter applies to the top-level variables only
- Make the table scrollable
- Use consistent naming for `VariableDetails` (code style)
=> Various fixes to the variables main area panel

src/breakpoints/body.tsx
https://github.com/jupyterlab/debugger/issues/408
@afshin
=> Remove slash from end of breakpoint path

README.md
Fixes #424.
Also related to #365 and #422.
=> Add a Usage section to the README

README.md
Added additional dependency to installation instructions. This should fix https://github.com/jupyterlab/debugger/issues/439.
=> Added nodejs to installation instructions

.github/workflows/tests.yml, README.md, binder/environment.yml
The kernelspec of xeus-python 0.8.0 contains the metadata field required by #457 .
=> Upgraded to xeus-python 0.8.0 and xeus 0.24.0

.github/workflows/tests.yml, README.md, binder/environment.yml
Fixes #452 
Follow-up to #463 as the pin shouldn't be needed anymore.
=> Unpin xeus

src/service.ts
=> Update API method names, refactor DebuggerService

src/service.ts
Reverts jupyterlab/debugger#465
=> Revert "Update API method names, refactor DebuggerService"

test/session.spec.ts
Evaluate request related with https://github.com/jupyterlab/debugger/issues/419
First commit contains test.
=> Evaluate request

package.json, test/debugger.spec.ts
Partial fix for #55. 
Add a couple of tests to check that the breakpoints are rendered in the debugger sidebar.
=> Add tests for the debugger sidebar

test/session.spec.ts
Add a new test to use the optional `condition` from the DAP `setBreakpoints` request: https://microsoft.github.io/debug-adapter-protocol/specification#Types_SourceBreakpoint
This is the first step before implementing conditional breakpoints in the debugger UI: https://github.com/jupyterlab/debugger/issues/498
=> Add a test for conditional breakpoints

.eslintrc.js, src/index.ts, src/panels/callstack/model.ts, src/panels/sources/body.ts, src/panels/sources/model.ts, src/panels/variables/grid.ts, src/panels/variables/index.ts, src/panels/variables/model.ts, src/panels/variables/tree.tsx, src/service.ts, src/tokens.ts
Addresses this comment: https://github.com/jupyterlab/debugger/issues/493#issuecomment-662955582
=> Move CallstackModel.IFrame to IDebugger.IStackFrame

binder/postBuild, package.json
=> v0.3.0-beta.6

src/handler.ts, src/index.ts, src/service.ts, src/sources.ts
=> Improve the handling of closed notebooks

.github/workflows/tests.yml, test/session.spec.ts
Update the tests to match the setup used in core lab, and skip the pagination test (https://github.com/jupyterlab/jupyterlab/commit/635694a58c145041553cd1c3dcea4382d4dd55f2).
=> Update CI to install with pip

src/service.ts
See https://github.com/jupyterlab/jupyterlab/pull/9402 for the explanation.
=> Clear models and signals upon continue response
