jupyterlab/debugger

.gitignore, README.md, package.json, src/session.ts, src/tokens.ts, tests/jest.config.js, tests/run-test.py, tests/src/session.spec.ts
Provide a simple `DebugSession` interface that can be used to send debug messages to the kernel.
=> Debug session interface

azure-pipelines.yml, package.json, tests/jest.config.js
Fixes #12.
Since we're still waiting to get access to GitHub actions, we can instead fall back to azure pipelines in the meantime.
- Add `jest-junit`
- Use `reporters` config from upstream `testutils`
- Add configuration for azure pipelines. See [Run pipelines with Anaconda environments](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04) for reference.
We need to use conda to be able to install `xeus-python`.
Here is what it looks like with the azure pipelines enabled on my fork: https://github.com/jtpio/debugger/pull/2
We still need to enable it for this repo and that should be enough.
Maybe we can also add other platforms (Windows) later on if that makes sense.
=> Add configuration for Azure Pipelines

README.md, azure-pipelines.yml, tests/run-test.py
`xeus-python 0.5` has been released and is available on conda forge.
Updating to this version simplifies the setup and using the debugger (the `xpython_debug_logs` folders are created automatically).
=> Require xeus-python 0.5

README.md, azure-pipelines.yml, src/session.ts, src/tokens.ts, tests/run-test.py, tests/src/session.spec.ts
Add several tests for `stackTrace`, `scopes` and `variablesReference`.
They can also serve as a reference for the protocol messages.
=> Add tests for stackTrace, scopes, variables

src/index.ts
This fixes the problem described by @jtpio [here](https://github.com/jupyterlab/debugger/pull/36#issuecomment-537105099).
The remaining issue is that executing the debugger command creates a new debugger instance while it should reuse the existing one.
=> Fixed debugger restore

package.json
Fixes https://github.com/jupyterlab/debugger/pull/36/files#r330992142
=> Move codemirror types to devDependencies

README.md, azure-pipelines.yml, src/tokens.ts, tests/src/session.spec.ts
This simplifies the handling of breakpoints, no need to pass the current execution count nor the next execution count anymore.
=> Upgraded to xeus-python 0.5.3 and replaced updateCell with dumpCell

README.md
Adding a short mention to the [kernelspy extension for JupyterLab](https://github.com/vidartf/jupyterlab-kernelspy).
This is quite useful to see the debug messages being sent over the network to and from the kernel.
cc @KsavinN @JohanMabille
=> Add mention to kernelspy extension to the README

src/debugger.ts, src/index.ts, src/session.ts, src/tokens.ts
- ~set ILayoutRestorer and ICommandPalette arguments as required~
- always displays the start and stop commands of the debugge
- start is enabled when a debugging session is available and the debugger has not started yet, disabled otherwise
- stop is enabled when a debugging session is available and the debugger has started, disabled otherwise.
Remaining issues:
- the '_isStarted' cache variable in the DebuggerSession object should be updated upon event notification
- the current implementation creates a new DebuggerSession each time a notebook gets the focus instead of restoring a previous existing session. This breaks the mechanism for enabling and disabling the start and stop commands. The session should be saved somewhere and restored, but I don't know yet the best way to achieve …
=> Start and stop always visible, enabled/disabled

package.json, tests/src/session.spec.ts
- Wait for the `stopped` debug event in the tests (instead of waiting for 2s)
- `tslint` check only for source files (for now, might reconsider that later)
- Re-add skipped tests
=> Wait for debug event in tests

style/variables.css
Just a quick style fix for the dark theme.
=> Fix search input for dark theme

src/breakpoints/body.tsx
Fixes the following issue with unmounted `BreakpointComponent` (React error on unmounted component):
=> Cleanup signals on unmount in BreakpointComponent

src/debugger.ts, src/editors/index.ts, src/index.ts, style/editors.css, style/index.css, tests/src/debugger.spec.ts
Fixes #56.
The typical usage would involve calling the `addEditor` method when receiving a message from kernel that we hit a breakpoint in a specific file. `addEditor` will show the content of the file that we stepping into (or a previous cell that was executed and then deleted).
This PR does not cover adding breakpoints to the read-only editors (can be done separately).
=> Add editors to the main area widget

README.md
Adding the following badge to the README:
[![Build Status](https://dev.azure.com/jupyterlab/jupyterlab/_apis/build/status/jupyterlab.debugger?branchName=master)](https://dev.azure.com/jupyterlab/jupyterlab/_build/latest?definitionId=3&branchName=master)
=> Add Azure Pipelines badge for build status

azure-pipelines.yml, src/index.ts, src/session.ts, src/tokens.ts
=> Restore debugger session state

src/session.ts
Fixes part of #76:
- wait for the session to be ready before restoring the state
- throw an error is the kernel is not available when sending messages
This could be improved later, for example by automatically restoring the debug state when the kernel is restarted.
=> Wait for the session to be ready before restoring state

src/debugger.ts, src/sidebar.ts
The debugger model is passed to the sidebar but not used.
=> Remove cyclic reference sidebar <-> model

src/breakpoints/index.ts, src/handlers/cell.ts, src/service.ts, src/tokens.ts
Initial steps to send the breakpoints to the kernel every time they change in the UI (added or deleted).
This is still a work in progress as there seems to be some issues w.r.t the handlers (messages sent multiple times).
Fixes #43
=> [WIP] Send breakpoints to the kernel on breakpointChanged

src/service.ts
Cleanup frames and variables when the execution has terminated.
=> Cleanup frames and variables on continued event

tslint.json
Fixes #31 
This should automatically sort imports on git commits for the files that have been changed.
We can also consider formatting all the existing files in one PR by running `jlpm run tslint` once.
=> Add tslint config for sorted imports

src/handlers/cell.ts, src/handlers/notebook.ts
Fixes #106.
edit: adding a screencast
=> Keep line numbers on when switching cells

src/breakpoints/body.tsx, src/breakpoints/index.ts, src/callstack/index.ts, src/editors/index.ts, src/handlers/cell.ts, src/handlers/console.ts, src/index.ts, src/service.ts, src/tokens.ts, src/variables/body/index.tsx, src/variables/index.ts
Fixes #117 and #110.
This removes the start and stop commands form the palette and implements the following behavior:
- when clicking on "Debugger" in the palette, the kernel of the notebook or console that has the focus starts a debugger if it can
- when opening a notebook or a console while the Debugger panel is already mounted, he associated kernel starts a debugger it it can.
- a running debugger is never manually stoppable (it will be stopped when the kernel dies).
=> Automagically starts the debugger if the kernel supports it

src/breakpoints/body.tsx, src/breakpoints/index.ts, src/handlers/cell.ts
Fixes #119 
The idea is to have one central place where breakpoints are added to the editor, that should be triggered when the model changes.
- Keep breakpoints sorted by line number
- Unify the naming of the breakpoints model methods
- Pass line numbers instead of `ILineInfo` to the breakpoint model
- Remove `clearedBreakpoints` signal
=> Set editors breakpoints on model changed

src/breakpoints/body.tsx, src/breakpoints/index.ts, src/debugger.ts, src/handlers/cell.ts, src/service.ts, src/variables/body/index.tsx, src/variables/index.ts
Fixes #134 
All models should have a `changed` signal.
Some models still have additional signals such as `_currentVariableChanged` that have been kept for now (we might or might not need them later on).
This PR is building on top of #132 and should be rebased once #132 is merged into master.
For a cleaner diff of the change, see https://github.com/jtpio/debugger/pull/4
=> Use changed signal for models

src/breakpoints/body.tsx
The name of the source was not displayed anymore.
=> Use source path for the breakpoints view

src/callstack/index.ts, src/debugger.ts, src/index.ts, style/callstack.css, tests/src/debugger.spec.ts
Fixes #81.
This change builds on top of #142, and should be rebased once #142 is merged.
=> Map callstack buttons to debug actions

src/breakpoints/index.ts, src/handlers/cell.ts
Fixes #159.
Not exactly sure why we had this in the first place. But the `onNewRenderLine` was modifying the breakpoints model directly and triggering CodeMirror issues (#159).
Instead we'll want to send the `dumpCell` and `setBreakpoints` requests via the service when a user modifies the content of a cell.
=> Remove onNewRenderLine

README.md, tests/src/service.spec.ts
Fixes #158.
```bash
jlpm run build && jlpm run test --testPathPatten="service\.spec\.ts"
```
=> Add tests for the DebugService

src/callstack/index.ts, src/index.ts, src/service.ts, src/tokens.ts, tests/src/debugger.spec.ts
Fixes #155 
There doesn't seem to be any straightforward way to continue the execution of a cell while ignoring all the breakpoints.
Altering the debug session state (removing and re-adding the breakpoints) could work, but could lead to edge cases such as the page being reloaded and losing all the breakpoints.
Another approach would be to support `disabled` breakpoints (#128):
- Click on `stop`
- Disable all breakpoints
- Wait for `execution_reply`
- Enable all breakpoints (or only the ones that were enabled before the `stop`)
=> Add the stop button to the callstack toolbar

src/handlers/cell.ts, src/handlers/notebook.ts, src/index.ts, style/breakpoints.css
Fixes #133 
Fixes #122 
and resolve the 
additional issue:
=> Resolve issues with Notebook Handler

src/handlers/cell.ts
Fixes #162.
The idea is to send the content of the cell and the list of breakpoints to the kernel, so that the next `execute_request` will be able to break using the up-to-date cell code.
=> Update breakpoints on cell content changed

src/index.ts
Fixes #174.
Something we discussed together with @KsavinN and @JohanMabille, and we decided to go with the `condensed` by default.
Eventually we can make this configurable via the `Advanced Settings`.
=> Change default mode to condensed

src/callstack/index.ts, src/handlers/cell.ts, src/service.ts
Fixes #173.
Leaving the "jump to code" aspect of #173 out of this scope for now (requires adding support for lookup using the hashes first).
=> Change line highlighting when switching callstack

src/index.ts
This should fix #96.
Add the sidebar to the layout restorer so it can be restored in the right area on page reload, and serializes it in the workspace file:
```json
"right": {
"collapsed": false,
"current": "debugger-sidebar",
"widgets": [
"debugger-sidebar"
]
}
```
=> Add the sidebar to the layout restorer

tests/src/session.spec.ts
This change adds two tests for the `DebugSession`.
This is in preparation for #169, and to test whether it is possible to retrieve the content for a `DebugProtocol.Source`.
At the moment the tests fail for both the `loadedSources` and `sources` request:
```
D00000.415: (while handling {'command': 'loadedSources', 'seq': 5, 'type': 'request'})
IDE <-- {
"type": "response",
"seq": 9,
"request_seq": 5,
"success": false,
"command": "loadedSources",
"message": "Unknown command",
"body": {}
}
```
```
D00000.599: (requested while handling {'command': 'source', 'seq': 7, 'type': 'request'})
PYD --> {
"type": "response",
"request_seq": 1000000005,
"success": false,
"command": "source",
"body": {
"content": ""
},
"seq": 22,
"message": "Source unavailable",
"pydevd_cmd_id": 502
}
```
=> Add tests for source and loadedSources

examples/index.ipynb, src/handlers/cell.ts, src/handlers/notebook.ts
This will fix #121.
There will still be more to refactor afterwards. Ideally we should be able to jump to any cells that are tracked by the debugger plugins. The logic could be shared between the notebook and console handlers.
Opening the content of the file / cell when it cannot be found in the current widgets can be done in #169.
=> Initial support for handling messages for other cells

src/handlers/cell.ts
Fixes #202.
The `value.changed` signal seems more appropriate.
=> Use the value.changed signal for the cell monitor

src/index.ts, src/service.ts, src/session.ts, src/tokens.ts, tests/src/service.spec.ts
=> Add support for the debugger flag in kernel info

src/index.ts, src/service.ts
Temporarily removing the check for `isDebuggingEnabled` when setting the debug session.
We'll probably want to adjust that in https://github.com/jupyterlab/debugger/issues/214 anyway.
=> Fix isDebuggingEnabled and remove the check

src/debugger.ts, src/editors/index.ts, src/handlers/console.ts, src/handlers/editor.ts, src/handlers/notebook.ts, src/index.ts
Fixes #200 
Fixes #211 
The goal is to make the `EditorHandler` aware of `CodeEditor.IEditor`, so we can reuse the same logic and hooks (gutter click, line highlighting and so on), when opening new editors in the main area widget.
- Remove `codeValue` from `Debugger.Model`
- `EditorHandler` handles a `CodeEditor.IEditor` instead of a `Cell`
- Remove notebook and console trackers from the handlers (a handler is for one widget)
- Re-use the `EditorHandler` for the main area read-only editors: add support for breakpoints and line highlighting
=> Add support for breakpoints and line highlighting in read-only editors

src/index.ts
It's resolve #209 . 
But seems like during creating new widget client not have already attached kernel  (it's exist some time gap):
=> no create handle for no supported kernels

package.json, src/index.ts, src/service.ts
Fixes #210. 
@JohanMabille @KsavinN @afshin if you use VS Code you might need to switch to the version with:
- Upgrade to TypeScript 3.7
- Update some parts to use [optional chaining](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#optional-chaining) and [nullish coalescing](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#nullish-coalescing)
=> Upgrade to TypeScript 3.7

src/index.ts
Fixes #178.
Simple fix to make it easier to change modes without having to use the palette.
We might want to add a real button later on, or something that make it easier to discover.
=> Add "Change Mode" to the sidebar context menu

package.json, src/handlers/editor.ts, src/handlers/file.ts, src/handlers/notebook.ts, src/index.ts, src/service.ts, src/session.ts, src/tokens.ts, tests/src/service.spec.ts
Fixes #225.
For now this still requires having a console open, and pressing `Shift-Enter` to execute the selected code.
Later on we will want to add a play or debug button to debug the file.
=> Add support for debugging files

package.json, src/handlers/editor.ts, src/handlers/notebook.ts, style/breakpoints.css
Fixes #238 
Allowing setting breakpoints in other cells even when they don't have the focus does feel more natural.
Also all the gutters initialized at the same when the notebook handler is created, which also feels more intuitive.
=> Allow setting breakpoints in out-of-focus cells

src/handlers/file.ts, src/handlers/notebook.ts, src/handlers/tracker.ts, src/index.ts
~This PR builds on top of #231 should be rebased when #231 is merged.~ [done]
This change lays the foundations for #176, #212 and #224.
This idea is have a plugin that depends on `INotebookTracker`, `IConsoleTracker` and `IEditorTracker` (all optional), that will be used to find the `CodeEditor.IEditor` from where an event originated. An event could be:
- a `stopped` event that contains the source path
- a click on a breakpoint (#224) (which also contains the source path)
The `TrackerHandler` iterates through all the widgets of the trackers to try to find a matching hash. When there is no match, this is where we could extend the logic to open files in the main area (#212) or to the read-only code editor view.
=> Add plugin to track notebooks, consoles and editors

src/breakpoints/body.tsx, src/breakpoints/index.ts, src/editors/index.ts, src/handlers/editor.ts, src/handlers/tracker.ts, style/breakpoints.css
Fixes #224.
This makes use of #234 to change the current active cell when a breakpoint is clicked.
=> Clickable breakpoints

src/index.ts, src/service.ts
Fixes #230. 
The debug service would keep a reference to the last used session. Instead we can do the same as for the model and set it to `null`.
=> Set session to null on model disposed

src/handlers/editor.ts, src/handlers/tracker.ts, src/service.ts, src/sources/index.ts, src/tokens.ts
Fixes #243.
Builds on top of #247. For a cleaner diff see commit https://github.com/jupyterlab/debugger/commit/5df41546222067a75428d8b474384aa789183ca6.
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jtpio/debugger/local-module-files?urlpath=/lab/tree/examples/index.ipynb)
This lets users set breakpoints in local modules and files. The breakpoints show up with the absolute path to the file in the `Breakpoints` split.
=> Add support for breakpoints in modules and files

src/index.ts
Fixes #250. 
This removes the internal `mount` command and makes sure only one `Environment` tab can be instantiated.
At the moment the sidebar is always recreated on refresh. Some ongoing work to toggle the debugger and manage its lifecycle is happening in #239 and #214.
=> Remove internal mount command

src/debugger.ts
This was suggested by @tgeorgeux to keep a uniform look for all the tab bar icons.
Also this will look less out of place when switching sidebar side:
=> Replace "Environment" by the jp-BugIcon

src/debugger.ts
Fixes #104. 
Small cleanup to remove the unused `Debugger.IOptions`.
=> Remove unused Debugger.IOptions

src/breakpoints/body.tsx, style/breakpoints.css
A quick pass on the breakpoints UI to:
- align the line numbers to the right
- handle the overflow for long source path
- add title attribute with the full path
=> Align breakpoint line numbers

src/breakpoints/index.ts, src/callstack/index.ts, src/sources/index.ts, src/variables/index.ts, style/sidebar.css, style/sources.css
Fixes #253.
Show the source path as we step into the code, so it's easier to know where the current execution has stopped.
=> Show source path above the read-only preview editor

package.json
`vscode-debugprotocol` was pinned to a specific version.
We can instead follow the same rule as for the other dependencies.
=> Use caret for the vscode-debugprotocol dependency

src/session.ts
We can use the kernel name for the `adapterID` field instead of hard-coding it to `python`.
=> Use kernel name as adapterID

src/debugger.ts, src/handlers/editor.ts, src/handlers/tracker.ts, src/service.ts, tests/src/service.spec.ts
This was briefly discussed a while ago. Having `model` as suffix to reference a model is might be unnecessary.
- something like `this.model.callstackModel.frame` becomes `this.model.callstack.frame`
- remove unused `Debugger.Model.IOptions`
=> Use more succint names for the sub-models

src/service.ts, src/session.ts
This is the first part of the wider kernel status handling from #76.
For now we have been using an internal `ensureSessionReady` method to make sure a session (and kernel) is ready before sending messages.
This moves the logic to a `ready` promise which doesn't assume the session is a `IClientSession`.
=> Move ensureSessionReady to a ready promise

src/index.ts
The session can be disposed before setting it to `null` when the debugger is closed.
=> Dispose the session on debugger closed

src/debugger.ts, src/index.ts, src/service.ts
Commands were not properly disabled when the debugger sidebar was closed.
This change should fix it.
=> Fix enabled commands on debugger closed

src/callstack/index.ts, src/debugger.ts, src/variables/index.ts
A quick cleanup to remove some unused parameters passed to `Callstack.Model` and `Variables.Model`.
=> Cleanup up sub-model constructors

src/index.ts, src/service.ts, src/session.ts, src/tokens.ts, tests/src/service.spec.ts
Fixes #268.
Check whether a kernel support debugging before restoring the session and sending the `debugInfo` message.
=> Check debugging is enabled before restoring the session

src/breakpoints/body.tsx, src/breakpoints/index.ts, src/handlers/editor.ts, style/breakpoints.css, style/editor.css, style/index.css
Part of #139:
- Format according to the style guide
- Rename CSS class name for the highlight and markers in the editors.
- Remove some `readonly` public attributes (not required)
=> Format breakpoint files to follow the code style

tests/src/service.spec.ts
Follow-up to #279.
Add tests for `service.hasStoppedThreads()`.
=> Add tests for service.hasStoppedThreads()

README.md, binder/environment.yml
Bump JupyterLab to 1.2 for Binder, because of an issue with the toggle button mentioned in #290.
=> Update JupyterLab to 1.2 for Binder

src/handlers/editor.ts, src/handlers/notebook.ts
A quick code cleanup.
Instead of iterating through all the cells in the notebook handler to clear the highlighting and breakpoint markers, we can do that in the `dispose` method of the `EditorHandler`.
=> Move editor cleanup to the handler dispose method

src/debugger.ts, src/handlers/tracker.ts, src/index.ts, src/service.ts
Fixes #168.
Alternative to #291. 
This introduces a new `clear()` method on the model to clear everything, and restore the breakpoints to an empty map.
This should also still support keeping the last debug session alive when switching between notebooks and widgets.
=> Clear the sidebar UI

README.md
Some environments (for example on mybinder.org), use `notebook` 5.x by default.
As a user, this results in not being able to see the toggle button to enable the debugger.
=> Add notebook>=6 to pre-requisites

src/index.ts
Remove `IStateDB` and `ILabShell` from the dependencies for the `@jupyterlab/debugger:main` plugin as they are not used.
=> Remove unused dependencies for the main plugin

style/breakpoints.css, style/callstack.css, style/sidebar.css
=> Make breakpoints and callstack scrollable

src/session.ts, tests/src/service.spec.ts, tests/src/session.spec.ts
This is an attempt at fixing the tests on CI, by using the same pattern as in core JupyterLab when it comes to initializing the session context and waiting for the kernel to be ready.
=> Attempt at fixing the tests on CI

package.json, src/debugger.ts
Fixes #355.
More info about the new `LabIcon` in:
- https://jupyterlab.readthedocs.io/en/latest/developer/extension_migration.html#using-the-new-icon-system-and-labicon
- https://github.com/jupyterlab/jupyterlab/tree/master/packages/ui-components#readme
- Example use for the file browser in the left area: https://github.com/jupyterlab/jupyterlab/blob/f17361c2d6ecf1b5ccae5b576266355150f09af2/packages/filebrowser-extension/src/index.ts#L296
=> Use LabIcon from ui-components for BugIcon

style/icons.css
Fixes #361. 
This pretty much reverts the change for the toggle button CSS from https://github.com/jupyterlab/debugger/pull/337.
Relying on the inner `svg` element was not a robust solution anyway in the long run.
This seems to fix the issue with `2.0.0rc0`:
=> Fix toggle button for JLab 2.0rc0

style/sources.css
=> Fix grey background for read-only editors

src/callstack/model.ts, src/variables/tree.tsx
=> Handle switching between two active debug sessions

package.json, schema/main.json, src/index.ts, src/variables/index.ts, src/variables/table.tsx, src/variables/tree.tsx
Fixes #179. 
Add a list to the debugger settings to be able to hide variables from the UI by default.
The current list of hidden variables is as follows:
```json
[
"display",
"ptvsd",
"__annotations__",
"__builtins__",
"__doc__",
"__loader__",
"__name__",
"__package__",
"__spec__"
]
```
Until now, these variables would show in the list of variables, but could lead to some confusion as some of them are related to the debugger implementation details (`ptvsd`).
This list can be seen as an equivalent to gitignore files, where users can choose which variables to hide and show.
In follow-up PRs, we can add a show / hide button to the Variables toolbar to toggle the variables directly.
=> Add a variable filter to the settings

src/variables/tree.tsx, style/variables.css
A quick pass on the tree view to tweak the CSS.
=> Use core lab caret icon for the tree view

README.md
Since a couple of the past issues were related to installation problems, let's update the instructions in the README to recommend creating a new environment before installing the extension.
=> Update the instructions to install the extension

.github/workflows/tests.yml, .github/workflows/wheel.yml
We can add the browser check step to CI, just like for other third-party extensions.
It is also now part of the default cookiecutter: 
https://github.com/jupyterlab/extension-cookiecutter-ts/blob/f33180f1c82bd6b310280d002d8a88f77005fcb9/.github/workflows/main.yml#L42
=> Add browser check to CI

schema/main.json
Fixes #425. 
I am also removing `_pydev_stop_at_break` which was appearing in the general scope.
Note: this will already solve the issue for the OSX and Windows wheels which were published after we prefixed the variables with _xpython. Hence I think this can get in.
=> Filter _xpython-prefixed variables

package.json
TypeScript 3.9 was released a couple days ago and a similar PR is currently open in the JupyterLab repo.
Blog post: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/
=> Update to TypeScript 3.9

.github/workflows/tests.yml
We should now be able to remove the `libgbm1` fix that was added in https://github.com/jupyterlab/debugger/pull/428 to fix the browser check.
=> Remove the temporary libgbm1 fix

.github/workflows/tests.yml, README.md, binder/environment.yml, src/debugger.ts, src/editor-finder.ts, src/handlers/tracker.ts, src/index.ts, src/service.ts
Refactor tracker.ts
Separated method find from tracker handler.
Created stand alone editor finder.
The plugin must be separated, instead of create the interface and token into tracker.ts, because if we don't do that will not be available in whole scope and will be a conflict with dependency cycle.
=> Add an editor-finder plugin

src/index.ts
These are currently exported and available as `CommandIDs.start` and `CommandIDs.stop`, but not used for now.
Let's remove them and re-add back if / when needed.
=> Remove unused start and stop command ids

src/index.ts
A small UX step towards https://github.com/jupyterlab/debugger/issues/289.
The sidebar is expanded when the `initialized` event is received, to let users know there is something on the right side:
=> Expand the sidebar on the initialized event

style/index.css
Fixes #480. 
Looking at the git history it seems like this is a leftover from the very early iterations that didn't get cleaned up.
=> Remove Font Awesome CSS

style/console.css, style/index.css
Fixes #477 
This change removes the styling applied to the document toolbar.
Since the toolbar is by default empty (although third-party extensions could add items), we might as well keep it at the start, the same for the console.
=> Fix file editor toolbar CSS

src/editor-finder.ts, src/handlers/tracker.ts, src/tokens.ts
Addresses item number 2 of https://github.com/jupyterlab/debugger/issues/493#issue-656656055.
To prepare the public interfaces before merging into JupyterLab core
=> IEditorFinder#find returns CodeEditor.IEditor[]

src/debugger.ts, src/index.ts
The original intent was to keep the model and the service separate, and let the service update the model.
However since the model is now created by the service:
https://github.com/jupyterlab/debugger/blob/4f56bb73da45e758416bd7a2c743f901cebfef72/src/service.ts#L40
We can then simplify a couple of things in the debugger sidebar.
=> Cleanup DebuggerModel in Sidebar

README.md
Fixes #64 
Move the Debug Protocol Overview documentation from #64 to README.md, so it is more visible.
This PR also updates the diagram to replace the `kernel_info` request by the `debugger` key lookup from the kernel spec instead.
=> Move the Debug protocol overview to README.md

src/index.ts
=> Hide the sidebar if no kernel supports debugging

src/index.ts, src/service.ts
Since we return arrays in the sources find method, we can use native methods to iterate through the results.
=> Remove unnecessary uses of each()

src/config.ts, test/config.spec.ts
Similar to the `hash` function look-up in the `DebuggerConfig`.
Since the `DebuggerConfig` relies on the caller to use `setTmpFileParams` and `setHashParams`, it can also throw an error if the tmp file parameters are not set.
This change also adds basic unit tests for the `DebuggerConfig`.
=> Throw if the config does not have tmp file params

src/service.ts, src/tokens.ts
cc @JohanMabille @SylvainCorlay @afshin 
The kernel *should* return an array of `DebugProtocol.SourceBreakpoint`: https://microsoft.github.io/debug-adapter-protocol/specification#Types_SourceBreakpoint
But the frontend was specifying a `DebugProtocol.Breakpoint` as the response type.
=> Switch to SourceBreakpoint for the debugInfo response

src/handlers/editor.ts, src/service.ts, src/tokens.ts, test/debugger.spec.ts, test/service.spec.ts
Fixes #515. 
Since this functionality is not implemented (frontend and backend), we can remove it from the interfaces.
=> Remove active from IDebugger.IBreakpoint

src/service.ts
This was brought in: https://github.com/jupyterlab/debugger/pull/457#discussion_r434455064
If `kernelSpecs` is not provided to the `DebuggerService`, then it is assumed that debugging is enabled, and the call to `DebuggerServicer#isAvailable` returns true regardless of the kernel connection passed as the argument.
This change should make it easier for users of `DebuggerService` in custom frontends and lab builds to enable debugging by default if they want to.
=> Make kernelspecs optional for DebuggerService

src/service.ts
This is a followup to: https://github.com/jupyterlab/debugger/pull/518
Returning `true` when calling `DebuggerServicer#isAvailable` and the `this._specsManager.specs.kernelspecs` are not available for the current kernel.
=> Return true from DebuggerServicer#isAvailable when spec is not available

src/tokens.ts
To follow the same convention as for the core plugins.
This was noticed while looking at the plugin dependency graph:
=> Rename IDebugger tokens

src/index.ts
Related to https://github.com/jupyterlab/debugger/issues/526
Adding PageConfig override to enable / disable the debugger extension.
If the override is set to true: enable the extension without checking kernel specs.
If the override is set to false: disable the extension.
If the override is not set: check the specs to determine whether or not the extension should be enabled.
=> Add page config override for debugger panel

src/handlers/editor.ts
Solution for problem with setting and removing breakpoints. Condition has been changed for case with empty string of `the_path`
=> Condition for empty string

src/handler.ts
Given a kernel that supports debugging, this change switches the order of the two following actions:
- restore the state using the `debugInfo` request
- add the button to the notebook toolbar
This makes it easier for kernel authors that are progressively implementing the protocol to see that the kernel is correctly supported by the debugger extension.
Otherwise we would wait for the response here:
https://github.com/jupyterlab/debugger/blob/9de87f02b5ee9403cf9c11bb276898e955a21e62/src/handler.ts#L295
And never show the button.
With this change, the button can be displayed in the toolbar:
Even though the `debugInfo` request has not been implemented yet:
=> Show the toolbar button before restoring the state

binder/postBuild
Looks like recent versions of JupyterLab 2.x fail to build on Binder due to high memory consumption.
Turning off minimization should help make the build succeed.
https://mybinder.org/v2/gh/jupyterlab/debugger/binder-minimize-false?urlpath=/lab/tree/examples/index.ipynb
=> Do not minimize on Binder

schema/main.json
Fixes #499 
Will port to https://github.com/jupyterlab/jupyterlab right after.
=> Add get_ipython to the variable filter

src/index.ts, src/sidebar.ts, src/tokens.ts
Adding ability to extend the Sidebar with a custom panel that will be displayed at the top (see screenshot below).
=> Adding an optional custom panel to the sidebar

README.md, binder/environment.yml, jest.config.js, package.json, src/config.ts, src/hash.ts, test/custom-env.js, yarn.lock
Fixes #538.
This change switches to using the murmurhash2 implementation from: https://github.com/jtpio/murmurhash2
Here is a report after digging into this and looking for different solutions. Posting a bit of information here so it's more convenient to refer to it in the future.
In https://github.com/jupyterlab/debugger/issues/538, we noticed that having non-ascii characters such as `€` in a code cell could be reproduced on the stable Binder (using `0.3.3`).
It was because the MurmurHash2 implementation in JS and the one used in `xeus-python` would not give the same result for the same input and seed.
`@jupyterlab/debugger` was using this implementation: https://github.com/mikolalysenko/murmurhash-js/blob/f19136e9f9c17f8cddc216ca3d44ec7c5c502f60/murmurhash2_gc.js#L14-L50, which …
=> Switch to a different murmurhash implementation to handle Unicode characters

src/service.ts
Fixes #555
Follow-up to https://github.com/jupyterlab/debugger/pull/514 and https://github.com/jupyter-xeus/xeus-python/pull/314, so the debugger frontend can handle the debug info reply properly.
=> Fix handling of source breakpoints

src/session.ts, test/service.spec.ts, test/session.spec.ts
Stopping the debugger should not stop the kernel.
=> Set terminateDebuggee to false

schema/main.json, src/panels/variables/grid.ts, src/panels/variables/index.ts, src/panels/variables/scope.tsx, src/panels/variables/tree.tsx, src/service.ts
Fixes #569 
This actually required going through the changes line by line, because of the differences between code bases (translator and strict null checks).
=> Handle multiple scopes
